### ISSUE TITLE
CT s.reset is not a function

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/proportion#10]
```
proportion : fuzz : built : load
https://bayes.colorado.edu/continuous-testing/snapshot-1586316573831/proportion/build/phet/proportion_en_phet.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzz&memoryLimit=1000
Query: fuzz&memoryLimit=1000
Uncaught TypeError: s.reset is not a function
TypeError: s.reset is not a function
    at listener (https://bayes.colorado.edu/continuous-testing/snapshot-1586316573831/proportion/build/phet/proportion_en_phet.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzz&memoryLimit=1000:4550:1039869)
    at t.listener (https://bayes.colorado.edu/continuous-testing/snapshot-1586316573831/proportion/build/phet/proportion_en_phet.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzz&memoryLimit=1000:4550:977289)
    at t.value (https://bayes.colorado.edu/continuous-testing/snapshot-1586316573831/proportion/build/phet/proportion_en_phet.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzz&memoryLimit=1000:4550:33929)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1586316573831/proportion/build/phet/proportion_en_phet.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzz&memoryLimit=1000:4550:46784
    at i.value (https://bayes.colorado.edu/continuous-testing/snapshot-1586316573831/proportion/build/phet/proportion_en_phet.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzz&memoryLimit=1000:4550:31093)
    at i.value (https://bayes.colorado.edu/continuous-testing/snapshot-1586316573831/proportion/build/phet/proportion_en_phet.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzz&memoryLimit=1000:4550:46988)
    at Tm.fire (https://bayes.colorado.edu/continuous-testing/snapshot-1586316573831/proportion/build/phet/proportion_en_phet.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzz&memoryLimit=1000:4550:803582)
    at i (https://bayes.colorado.edu/continuous-testing/snapshot-1586316573831/proportion/build/phet/proportion_en_phet.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzz&memoryLimit=1000:4550:802879)
    at t.value (https://bayes.colorado.edu/continuous-testing/snapshot-1586316573831/proportion/build/phet/proportion_en_phet.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzz&memoryLimit=1000:4550:33929)
    at i.value (https://bayes.colorado.edu/continuous-testing/snapshot-1586316573831/proportion/build/phet/proportion_en_phet.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzz&memoryLimit=1000:4550:37287)
id: Bayes Chrome
Approximately 4/7/2020, 9:29:33 PM
proportion : fuzz : built : run
https://bayes.colorado.edu/continuous-testing/snapshot-1586316573831/proportion/build/phet/proportion_en_phet.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzz&memoryLimit=1000
Query: fuzz&memoryLimit=1000
Uncaught TypeError: s.reset is not a function
TypeError: s.reset is not a function
    at listener (https://bayes.colorado.edu/continuous-testing/snapshot-1586316573831/proportion/build/phet/proportion_en_phet.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzz&memoryLimit=1000:4550:1039869)
    at t.listener (https://bayes.colorado.edu/continuous-testing/snapshot-1586316573831/proportion/build/phet/proportion_en_phet.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzz&memoryLimit=1000:4550:977289)
    at t.value (https://bayes.colorado.edu/continuous-testing/snapshot-1586316573831/proportion/build/phet/proportion_en_phet.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzz&memoryLimit=1000:4550:33929)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1586316573831/proportion/build/phet/proportion_en_phet.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzz&memoryLimit=1000:4550:46784
    at i.value (https://bayes.colorado.edu/continuous-testing/snapshot-1586316573831/proportion/build/phet/proportion_en_phet.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzz&memoryLimit=1000:4550:31093)
    at i.value (https://bayes.colorado.edu/continuous-testing/snapshot-1586316573831/proportion/build/phet/proportion_en_phet.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzz&memoryLimit=1000:4550:46988)
    at Tm.fire (https://bayes.colorado.edu/continuous-testing/snapshot-1586316573831/proportion/build/phet/proportion_en_phet.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzz&memoryLimit=1000:4550:803582)
    at i (https://bayes.colorado.edu/continuous-testing/snapshot-1586316573831/proportion/build/phet/proportion_en_phet.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzz&memoryLimit=1000:4550:802879)
    at t.value (https://bayes.colorado.edu/continuous-testing/snapshot-1586316573831/proportion/build/phet/proportion_en_phet.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzz&memoryLimit=1000:4550:33929)
    at i.value (https://bayes.colorado.edu/continuous-testing/snapshot-1586316573831/proportion/build/phet/proportion_en_phet.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzz&memoryLimit=1000:4550:37287)
id: Bayes Chrome
Approximately 4/7/2020, 9:29:33 PM
proportion : fuzz : require.js : run
https://bayes.colorado.edu/continuous-testing/snapshot-1586316573831/proportion/proportion_en.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&brand=phet&ea&fuzz&memoryLimit=1000
Query: brand=phet&ea&fuzz&memoryLimit=1000
Uncaught TypeError: this.reset is not a function
TypeError: this.reset is not a function
    at listener (https://bayes.colorado.edu/continuous-testing/snapshot-1586316573831/proportion/js/free-objects/view/FreeObjectsScreenView.js:96:14)
    at ResetAllButton.options.listener (https://bayes.colorado.edu/continuous-testing/snapshot-1586316573831/scenery-phet/js/buttons/ResetAllButton.js:60:5)
    at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/snapshot-1586316573831/axon/js/TinyEmitter.js:65:53)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1586316573831/axon/js/Emitter.js:33:29
    at Emitter.execute (https://bayes.colorado.edu/continuous-testing/snapshot-1586316573831/axon/js/Action.js:224:18)
    at Emitter.emit (https://bayes.colorado.edu/continuous-testing/snapshot-1586316573831/axon/js/Emitter.js:58:19)
    at PushButtonModel.fire (https://bayes.colorado.edu/continuous-testing/snapshot-1586316573831/sun/js/buttons/PushButtonModel.js:158:23)
    at downPropertyObserver (https://bayes.colorado.edu/continuous-testing/snapshot-1586316573831/sun/js/buttons/PushButtonModel.js:90:14)
    at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/snapshot-1586316573831/axon/js/TinyEmitter.js:65:53)
    at BooleanProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/snapshot-1586316573831/axon/js/Property.js:276:25)
id: Bayes Chrome
Approximately 4/7/2020, 9:29:33 PM
proportion : fuzz : require.js : run
https://bayes.colorado.edu/continuous-testing/snapshot-1586316573831/proportion/proportion_en.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&brand=phet&ea&fuzz&memoryLimit=1000
Query: brand=phet&ea&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: Cannot fire when already firing
Error: Assertion failed: Cannot fire when already firing
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1586316573831/assert/js/assert.js:22:13)
    at PushButtonModel.fire (https://bayes.colorado.edu/continuous-testing/snapshot-1586316573831/sun/js/buttons/PushButtonModel.js:156:15)
    at downPropertyObserver (https://bayes.colorado.edu/continuous-testing/snapshot-1586316573831/sun/js/buttons/PushButtonModel.js:90:14)
    at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/snapshot-1586316573831/axon/js/TinyEmitter.js:65:53)
    at BooleanProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/snapshot-1586316573831/axon/js/Property.js:276:25)
    at BooleanProperty.set (https://bayes.colorado.edu/continuous-testing/snapshot-1586316573831/axon/js/Property.js:175:14)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1586316573831/sun/js/buttons/ButtonModel.js:165:25
    at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/snapshot-1586316573831/axon/js/TinyEmitter.js:65:53)
    at BooleanProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/snapshot-1586316573831/axon/js/Property.js:276:25)
    at BooleanProperty.set (https://bayes.colorado.edu/continuous-testing/snapshot-1586316573831/axon/js/Property.js:175:14)
id: Bayes Chrome
Approximately 4/7/2020, 9:29:33 PM
proportion : interactive-description-fuzz : built : run
https://bayes.colorado.edu/continuous-testing/snapshot-1586316573831/proportion/build/phet/proportion_en_phet.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzz&supportsDescriptions&memoryLimit=1000
Query: fuzz&supportsDescriptions&memoryLimit=1000
Uncaught TypeError: s.reset is not a function
TypeError: s.reset is not a function
    at listener (https://bayes.colorado.edu/continuous-testing/snapshot-1586316573831/proportion/build/phet/proportion_en_phet.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzz&supportsDescriptions&memoryLimit=1000:4550:1039869)
    at t.listener (https://bayes.colorado.edu/continuous-testing/snapshot-1586316573831/proportion/build/phet/proportion_en_phet.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzz&supportsDescriptions&memoryLimit=1000:4550:977289)
    at t.value (https://bayes.colorado.edu/continuous-testing/snapshot-1586316573831/proportion/build/phet/proportion_en_phet.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzz&supportsDescriptions&memoryLimit=1000:4550:33929)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1586316573831/proportion/build/phet/proportion_en_phet.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzz&supportsDescriptions&memoryLimit=1000:4550:46784
    at i.value (https://bayes.colorado.edu/continuous-testing/snapshot-1586316573831/proportion/build/phet/proportion_en_phet.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzz&supportsDescriptions&memoryLimit=1000:4550:31093)
    at i.value (https://bayes.colorado.edu/continuous-testing/snapshot-1586316573831/proportion/build/phet/proportion_en_phet.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzz&supportsDescriptions&memoryLimit=1000:4550:46988)
    at Tm.fire (https://bayes.colorado.edu/continuous-testing/snapshot-1586316573831/proportion/build/phet/proportion_en_phet.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzz&supportsDescriptions&memoryLimit=1000:4550:803582)
    at i (https://bayes.colorado.edu/continuous-testing/snapshot-1586316573831/proportion/build/phet/proportion_en_phet.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzz&supportsDescriptions&memoryLimit=1000:4550:802879)
    at t.value (https://bayes.colorado.edu/continuous-testing/snapshot-1586316573831/proportion/build/phet/proportion_en_phet.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzz&supportsDescriptions&memoryLimit=1000:4550:33929)
    at i.value (https://bayes.colorado.edu/continuous-testing/snapshot-1586316573831/proportion/build/phet/proportion_en_phet.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzz&supportsDescriptions&memoryLimit=1000:4550:37287)
id: Bayes Chrome
Approximately 4/7/2020, 9:29:33 PM
proportion : interactive-description-fuzz : built : run
https://bayes.colorado.edu/continuous-testing/snapshot-1586316573831/proportion/build/phet/proportion_en_phet.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzz&supportsDescriptions&memoryLimit=1000
Query: fuzz&supportsDescriptions&memoryLimit=1000
Uncaught TypeError: s.reset is not a function
TypeError: s.reset is not a function
    at listener (https://bayes.colorado.edu/continuous-testing/snapshot-1586316573831/proportion/build/phet/proportion_en_phet.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzz&supportsDescriptions&memoryLimit=1000:4550:1049531)
    at t.listener (https://bayes.colorado.edu/continuous-testing/snapshot-1586316573831/proportion/build/phet/proportion_en_phet.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzz&supportsDescriptions&memoryLimit=1000:4550:977289)
    at t.value (https://bayes.colorado.edu/continuous-testing/snapshot-1586316573831/proportion/build/phet/proportion_en_phet.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzz&supportsDescriptions&memoryLimit=1000:4550:33929)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1586316573831/proportion/build/phet/proportion_en_phet.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzz&supportsDescriptions&memoryLimit=1000:4550:46784
    at i.value (https://bayes.colorado.edu/continuous-testing/snapshot-1586316573831/proportion/build/phet/proportion_en_phet.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzz&supportsDescriptions&memoryLimit=1000:4550:31093)
    at i.value (https://bayes.colorado.edu/continuous-testing/snapshot-1586316573831/proportion/build/phet/proportion_en_phet.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzz&supportsDescriptions&memoryLimit=1000:4550:46988)
    at Tm.fire (https://bayes.colorado.edu/continuous-testing/snapshot-1586316573831/proportion/build/phet/proportion_en_phet.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzz&supportsDescriptions&memoryLimit=1000:4550:803582)
    at i (https://bayes.colorado.edu/continuous-testing/snapshot-1586316573831/proportion/build/phet/proportion_en_phet.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzz&supportsDescriptions&memoryLimit=1000:4550:802879)
    at t.value (https://bayes.colorado.edu/continuous-testing/snapshot-1586316573831/proportion/build/phet/proportion_en_phet.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzz&supportsDescriptions&memoryLimit=1000:4550:33929)
    at i.value (https://bayes.colorado.edu/continuous-testing/snapshot-1586316573831/proportion/build/phet/proportion_en_phet.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzz&supportsDescriptions&memoryLimit=1000:4550:37287)
id: Bayes Chrome
Approximately 4/7/2020, 9:29:33 PM
proportion : interactive-description-fuzz : require.js : run
https://bayes.colorado.edu/continuous-testing/snapshot-1586316573831/proportion/proportion_en.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&brand=phet&ea&fuzz&supportsDescriptions&memoryLimit=1000
Query: brand=phet&ea&fuzz&supportsDescriptions&memoryLimit=1000
Uncaught TypeError: this.reset is not a function
TypeError: this.reset is not a function
    at listener (https://bayes.colorado.edu/continuous-testing/snapshot-1586316573831/proportion/js/free-objects/view/FreeObjectsScreenView.js:96:14)
    at ResetAllButton.options.listener (https://bayes.colorado.edu/continuous-testing/snapshot-1586316573831/scenery-phet/js/buttons/ResetAllButton.js:60:5)
    at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/snapshot-1586316573831/axon/js/TinyEmitter.js:65:53)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1586316573831/axon/js/Emitter.js:33:29
    at Emitter.execute (https://bayes.colorado.edu/continuous-testing/snapshot-1586316573831/axon/js/Action.js:224:18)
    at Emitter.emit (https://bayes.colorado.edu/continuous-testing/snapshot-1586316573831/axon/js/Emitter.js:58:19)
    at PushButtonModel.fire (https://bayes.colorado.edu/continuous-testing/snapshot-1586316573831/sun/js/buttons/PushButtonModel.js:158:23)
    at downPropertyObserver (https://bayes.colorado.edu/continuous-testing/snapshot-1586316573831/sun/js/buttons/PushButtonModel.js:90:14)
    at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/snapshot-1586316573831/axon/js/TinyEmitter.js:65:53)
    at BooleanProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/snapshot-1586316573831/axon/js/Property.js:276:25)
id: Bayes Chrome
Approximately 4/7/2020, 9:29:33 PM
proportion : interactive-description-fuzz : require.js : run
https://bayes.colorado.edu/continuous-testing/snapshot-1586316573831/proportion/proportion_en.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&brand=phet&ea&fuzz&supportsDescriptions&memoryLimit=1000
Query: brand=phet&ea&fuzz&supportsDescriptions&memoryLimit=1000
Uncaught TypeError: this.reset is not a function
TypeError: this.reset is not a function
    at listener (https://bayes.colorado.edu/continuous-testing/snapshot-1586316573831/proportion/js/bar/view/BarScreenView.js:64:14)
    at ResetAllButton.options.listener (https://bayes.colorado.edu/continuous-testing/snapshot-1586316573831/scenery-phet/js/buttons/ResetAllButton.js:60:5)
    at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/snapshot-1586316573831/axon/js/TinyEmitter.js:65:53)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1586316573831/axon/js/Emitter.js:33:29
    at Emitter.execute (https://bayes.colorado.edu/continuous-testing/snapshot-1586316573831/axon/js/Action.js:224:18)
    at Emitter.emit (https://bayes.colorado.edu/continuous-testing/snapshot-1586316573831/axon/js/Emitter.js:58:19)
    at PushButtonModel.fire (https://bayes.colorado.edu/continuous-testing/snapshot-1586316573831/sun/js/buttons/PushButtonModel.js:158:23)
    at downPropertyObserver (https://bayes.colorado.edu/continuous-testing/snapshot-1586316573831/sun/js/buttons/PushButtonModel.js:90:14)
    at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/snapshot-1586316573831/axon/js/TinyEmitter.js:65:53)
    at BooleanProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/snapshot-1586316573831/axon/js/Property.js:276:25)
id: Bayes Chrome
Approximately 4/7/2020, 9:29:33 PM
proportion : interactive-description-fuzzBoard : built : run
https://bayes.colorado.edu/continuous-testing/snapshot-1586316573831/proportion/build/phet/proportion_en_phet.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzzBoard&supportsDescriptions&memoryLimit=1000
Query: fuzzBoard&supportsDescriptions&memoryLimit=1000
Uncaught TypeError: s.reset is not a function
TypeError: s.reset is not a function
    at listener (https://bayes.colorado.edu/continuous-testing/snapshot-1586316573831/proportion/build/phet/proportion_en_phet.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzzBoard&supportsDescriptions&memoryLimit=1000:4550:1049531)
    at t.listener (https://bayes.colorado.edu/continuous-testing/snapshot-1586316573831/proportion/build/phet/proportion_en_phet.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzzBoard&supportsDescriptions&memoryLimit=1000:4550:977289)
    at t.value (https://bayes.colorado.edu/continuous-testing/snapshot-1586316573831/proportion/build/phet/proportion_en_phet.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzzBoard&supportsDescriptions&memoryLimit=1000:4550:33929)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1586316573831/proportion/build/phet/proportion_en_phet.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzzBoard&supportsDescriptions&memoryLimit=1000:4550:46784
    at i.value (https://bayes.colorado.edu/continuous-testing/snapshot-1586316573831/proportion/build/phet/proportion_en_phet.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzzBoard&supportsDescriptions&memoryLimit=1000:4550:31093)
    at i.value (https://bayes.colorado.edu/continuous-testing/snapshot-1586316573831/proportion/build/phet/proportion_en_phet.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzzBoard&supportsDescriptions&memoryLimit=1000:4550:46988)
    at Tm.fire (https://bayes.colorado.edu/continuous-testing/snapshot-1586316573831/proportion/build/phet/proportion_en_phet.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzzBoard&supportsDescriptions&memoryLimit=1000:4550:803582)
    at i (https://bayes.colorado.edu/continuous-testing/snapshot-1586316573831/proportion/build/phet/proportion_en_phet.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzzBoard&supportsDescriptions&memoryLimit=1000:4550:802879)
    at t.value (https://bayes.colorado.edu/continuous-testing/snapshot-1586316573831/proportion/build/phet/proportion_en_phet.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzzBoard&supportsDescriptions&memoryLimit=1000:4550:33929)
    at i.value (https://bayes.colorado.edu/continuous-testing/snapshot-1586316573831/proportion/build/phet/proportion_en_phet.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzzBoard&supportsDescriptions&memoryLimit=1000:4550:37287)
id: Bayes Chrome
Approximately 4/7/2020, 9:29:33 PM
proportion : interactive-description-fuzzBoard : require.js : run
https://bayes.colorado.edu/continuous-testing/snapshot-1586316573831/proportion/proportion_en.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&brand=phet&ea&fuzzBoard&supportsDescriptions&memoryLimit=1000
Query: brand=phet&ea&fuzzBoard&supportsDescriptions&memoryLimit=1000
Uncaught TypeError: this.reset is not a function
TypeError: this.reset is not a function
    at listener (https://bayes.colorado.edu/continuous-testing/snapshot-1586316573831/proportion/js/bar/view/BarScreenView.js:64:14)
    at ResetAllButton.options.listener (https://bayes.colorado.edu/continuous-testing/snapshot-1586316573831/scenery-phet/js/buttons/ResetAllButton.js:60:5)
    at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/snapshot-1586316573831/axon/js/TinyEmitter.js:65:53)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1586316573831/axon/js/Emitter.js:33:29
    at Emitter.execute (https://bayes.colorado.edu/continuous-testing/snapshot-1586316573831/axon/js/Action.js:224:18)
    at Emitter.emit (https://bayes.colorado.edu/continuous-testing/snapshot-1586316573831/axon/js/Emitter.js:58:19)
    at PushButtonModel.fire (https://bayes.colorado.edu/continuous-testing/snapshot-1586316573831/sun/js/buttons/PushButtonModel.js:158:23)
    at downPropertyObserver (https://bayes.colorado.edu/continuous-testing/snapshot-1586316573831/sun/js/buttons/PushButtonModel.js:90:14)
    at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/snapshot-1586316573831/axon/js/TinyEmitter.js:65:53)
    at BooleanProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/snapshot-1586316573831/axon/js/Property.js:276:25)
id: Bayes Chrome
Approximately 4/7/2020, 9:29:33 PM
proportion : xss-fuzz : run
https://bayes.colorado.edu/continuous-testing/snapshot-1586316573831/proportion/proportion_en.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Query: brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Uncaught TypeError: this.reset is not a function
TypeError: this.reset is not a function
    at listener (https://bayes.colorado.edu/continuous-testing/snapshot-1586316573831/proportion/js/free-objects/view/FreeObjectsScreenView.js:96:14)
    at ResetAllButton.options.listener (https://bayes.colorado.edu/continuous-testing/snapshot-1586316573831/scenery-phet/js/buttons/ResetAllButton.js:60:5)
    at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/snapshot-1586316573831/axon/js/TinyEmitter.js:65:53)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1586316573831/axon/js/Emitter.js:33:29
    at Emitter.execute (https://bayes.colorado.edu/continuous-testing/snapshot-1586316573831/axon/js/Action.js:224:18)
    at Emitter.emit (https://bayes.colorado.edu/continuous-testing/snapshot-1586316573831/axon/js/Emitter.js:58:19)
    at PushButtonModel.fire (https://bayes.colorado.edu/continuous-testing/snapshot-1586316573831/sun/js/buttons/PushButtonModel.js:158:23)
    at downPropertyObserver (https://bayes.colorado.edu/continuous-testing/snapshot-1586316573831/sun/js/buttons/PushButtonModel.js:90:14)
    at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/snapshot-1586316573831/axon/js/TinyEmitter.js:65:53)
    at BooleanProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/snapshot-1586316573831/axon/js/Property.js:276:25)
id: Bayes Chrome
Approximately 4/7/2020, 9:29:33 PM
proportion : xss-fuzz : run
https://bayes.colorado.edu/continuous-testing/snapshot-1586316573831/proportion/proportion_en.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Query: brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Uncaught TypeError: this.reset is not a function
TypeError: this.reset is not a function
    at listener (https://bayes.colorado.edu/continuous-testing/snapshot-1586316573831/proportion/js/bar/view/BarScreenView.js:64:14)
    at ResetAllButton.options.listener (https://bayes.colorado.edu/continuous-testing/snapshot-1586316573831/scenery-phet/js/buttons/ResetAllButton.js:60:5)
    at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/snapshot-1586316573831/axon/js/TinyEmitter.js:65:53)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1586316573831/axon/js/Emitter.js:33:29
    at Emitter.execute (https://bayes.colorado.edu/continuous-testing/snapshot-1586316573831/axon/js/Action.js:224:18)
    at Emitter.emit (https://bayes.colorado.edu/continuous-testing/snapshot-1586316573831/axon/js/Emitter.js:58:19)
    at PushButtonModel.fire (https://bayes.colorado.edu/continuous-testing/snapshot-1586316573831/sun/js/buttons/PushButtonModel.js:158:23)
    at downPropertyObserver (https://bayes.colorado.edu/continuous-testing/snapshot-1586316573831/sun/js/buttons/PushButtonModel.js:90:14)
    at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/snapshot-1586316573831/axon/js/TinyEmitter.js:65:53)
    at BooleanProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/snapshot-1586316573831/axon/js/Property.js:276:25)
id: Bayes Chrome
Approximately 4/7/2020, 9:29:33 PM
```

**Comment by zepumph** [comment]
Thanks! Fixed above. Fuzzing locally is working. Closing
